import Header from '@/components/Header'
import './globals.css'
import {Montserrat} from "next/font/google";
import Footer from "@/components/Footer"

export const metadata = {
  title: 'Kongmia',
  description: 'Generated by create next app',
};

const montserrat = Montserrat ({
subsets: ["latin"],
display: "swap",
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={montserrat.className}>
      <body>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  )
}
